name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Update package.json version
        run: |
          git fetch --tags
          VERSION=$(git rev-parse HEAD)
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo '{\"version\": \"'$VERSION'\"}' > package.json"

      - name: Install PM2 globally using bun
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            ~/.bun/bin/bun add pm2 -g
          EOF

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            set -e
            cd ~/vanjacloud.remote
            git fetch origin && git reset --hard origin/$(git branch --show-current) && git clean -fd
            ~/.bun/bin/bun install
            if ~/.bun/bin/pm2 list | grep -q vanjacloud; then
              ~/.bun/bin/pm2 reload vanjacloud
            else
              ~/.bun/bin/pm2 start 'bun --hot run src/main.ts' --name vanjacloud
            fi
          EOF

      - name: Verify deployment
        run: |
          VERSION=$(git rev-parse HEAD)
          RESPONSE=$(curl -s http://remote.vanja.oljaca.me:3000/version)
          if [ "$RESPONSE" != "$VERSION" ]; then
            echo "Deployment verification failed. Expected version $VERSION, got $RESPONSE"
            exit 1
          else
            echo "Deployment verified successfully."
          fi
