name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            set -e
            cd ~/vanjacloud.remote
            # Your deployment commands go here
            git fetch origin && git reset --hard origin/$(git branch --show-current) && git clean -fd
            /home/vanjacloud/.bun/bin/bun install
          EOF
